version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && python main.py"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network: